---
  - name: Domain Join | 01. Pre-flight валидация переменных и окружения
    ansible.builtin.import_tasks: 01_pre_flight.yml

  - name: Domain Join | 02. Настройка FQDN
    ansible.builtin.import_tasks: 02_configure_fqdn.yml

  - name: Domain Join | 03. Подключение к домену
    ansible.builtin.import_tasks: 03_domain_join.yml