---
- name: System APT | 01. Pre-flight валидация переменных и окружения
  ansible.builtin.import_tasks: 01_pre_flight.yml

- name: System APT | 02. Настройка базовых репозиториев ОС
  ansible.builtin.import_tasks: 02_base_repos.yml

- name: System APT | 03. Импорт сторонних PGP/GPG ключей
  ansible.builtin.import_tasks: 03_gpg_keys.yml

- name: System APT | 04. Деплой сторонних репозиториев и установка пакетов
  ansible.builtin.import_tasks: 04_apt_packages.yml