- name: Pre-flight | Проверка существования указанных SSH ключей
  ansible.builtin.stat:
    path: "{{ item }}"
  loop: "{{ ssh_host_keys }}"
  register: ssh_host_key_stats

- name: Pre-flight | Валидация статуса существования указанных SSH ключей
  ansible.builtin.assert:
    that:
      - item.stat.exists
    fail_msg: "[CRITICAL ERROR]: SSH ключ {{ item.item }} не найден!"
  loop: "{{ ssh_host_key_stats.results | default([]) }}"
  loop_control:
    label: "{{ item.item }}"

- name: Pre-flight | Проверка указанных параметров SSH
  ansible.builtin.assert:
    that:
      - ssh_port | int > 0 and ssh_port | int <= 65535
      - ssh_max_auth_tries | int > 0 and ssh_max_auth_tries | int <= 10
      - ssh_client_alive_interval | int >= 0
      - ssh_max_sessions | int > 0
      - ssh_password_authentication in ['yes', 'no']
      - ssh_pubkey_authentication in ['yes', 'no']
      - ssh_password_authentication == 'yes' or ssh_pubkey_authentication == 'yes'
    fail_msg: "[CRITICAL ERROR]: Ошибка в заданных параметрах SSH!"

- name: Pre-flight | Проверка параметров баннера
  ansible.builtin.assert:
    that:
      - ssh_banner_path | default('') | length > 0
      - ssh_company_name | default('') | length > 0
      - ssh_security_contacts | default([]) | length > 0
    fail_msg: >-
      [CRITICAL ERROR]:
      ssh_enable_banner задан 'true', но одна из обязательных переменных не задана 
      (ssh_banner_path, ssh_company_name, ssh_security_contacts) не должны быть пустыми!
  when: ssh_enable_banner | default(false) | bool

- name: Pre-flight | Предотвращение блокировки при отключенной авторизации по паролю
  block:
    - name: Проверка наличия authorized_keys для {{ ansible_user }}
      ansible.builtin.stat:
        path: "~{{ ansible_user }}/.ssh/authorized_keys"
      register: auth_keys_check

    - name: Валидация наличия SSH ключей в authorized_keys
      ansible.builtin.assert:
        that:
          - auth_keys_check.stat.exists
          - auth_keys_check.stat.size > 0
        fail_msg: "[CRITICAL ERROR]: Отключен вход по паролю, но файл authorized_keys для пользователя {{ ansible_user }} отсутствует или пуст!"
  when: 
    - ssh_password_authentication == "no"
    - ssh_pubkey_authentication == "yes"

- name: Pre-flight | Проверка самоблокировки через AllowUsers
  ansible.builtin.fail:
    msg: "[CRITICAL ERROR]: Текущий пользователь {{ ansible_user }} отсутствует в ssh_allow_users. Вы потеряете доступ!"
  when:
    - ssh_allow_users | default([]) | length > 0
    - ansible_user not in ssh_allow_users