---
  - name: Security PAM SSH | 01. Pre-flight валидация переменных и окружения
    ansible.builtin.import_tasks: 01_pre_flight.yml

  - name: Security PAM SSH | 02. Настройка {{ pam_ssh_access_file }}
    ansible.builtin.import_tasks: 02_configure_access_conf.yml

  - name: Security PAM SSH | 03. Настройка /etc/pam.d/sshd
    ansible.builtin.import_tasks: 03_configure_sshd_pam.yml

  - name: Security PAM SSH | 04. Настройка sudo GSSAPI
    ansible.builtin.include_tasks: 04_configure_sudo_gssapi.yml
    when: pam_ssh_gssapi_sudo_enable | default(false) | bool