---
- name: Zabbix Agent | Сбор информации о пакетах
  ansible.builtin.package_facts:
    manager: auto

- name: Zabbix Agent | Сбор информации о сервисах
  ansible.builtin.service_facts:

- name: Zabbix Agent | 01. Pre-flight валидация ОС и Zabbix Server-а
  ansible.builtin.import_tasks: 01_pre_flight.yml

- name: Zabbix Agent | 02. Удаление старого агента
  ansible.builtin.include_tasks: 02_cleanup_old_agent.yml
  when: >
    'zabbix-agent' in ansible_facts.packages or
    'zabbix-agent.service' in ansible_facts.services

- name: Zabbix Agent | 03. Установка zabbix-agent2 на Astra Linux
  ansible.builtin.include_tasks: 03_install_astra.yml
  when:
    - "'zabbix-agent2' not in ansible_facts.packages or zabbix_agent_package_state == 'latest'"
    - ansible_facts['distribution'] == 'Astra Linux'

- name: Zabbix Agent | 03. Установка zabbix-agent2 на Debian
  ansible.builtin.include_tasks: 03_install_debian.yml
  when:
    - "'zabbix-agent2' not in ansible_facts.packages or zabbix_agent_package_state == 'latest'"
    - ansible_facts['distribution'] == 'Debian'

- name: Zabbix Agent | 04. Генерация TLS PSK
  ansible.builtin.import_tasks: 04_psk.yml
  when: zabbix_agent_tls_enable | default(true) | bool

- name: Zabbix Agent | 05. Настройка скриптов и sudoers
  ansible.builtin.import_tasks: 05_configure.yml

- name: Zabbix Agent | 06. Регистрация на Zabbix Server
  ansible.builtin.import_tasks: 06_zabbix_api.yml