---
- name: Security XRDP | 01. Pre-flight валидация переменных и окружения
  ansible.builtin.import_tasks: 01_pre_flight.yml

- name: Security PAM XRDP | 02. Настройка {{ pam_xrdp_access_file }}
  ansible.builtin.import_tasks: 02_configure_access_conf.yml

- name: Security PAM XRDP | 03. Настройка /etc/pam.d/xrdp-sesman
  ansible.builtin.import_tasks: 03_configure_xrdp_pam.yml

- name: Security XRDP | 04. Настройка sesman.ini
  ansible.builtin.import_tasks: 04_configure_xrdp_sesman.yml

- name: Security FLY | 05. Настройка Fly WM
  ansible.builtin.import_tasks: 05_configure_fly.yml